backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "flavours"
    label: "Flavours"
    files:
      - file: "content/flavours.json"
        label: "Flavour list"
        name: "flavours"
        fields:
          - label: "Flavours"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Photo", name: "image", widget: "image", required: false }

  - name: "gallery"
    label: "Gallery"
    files:
      - file: "content/gallery.json"
        label: "Gallery photos"
        name: "gallery"
        fields:
          - label: "Photos"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Photo", name: "image", widget: "image" }
